{{- if .Values.prometheus.serviceMonitor.enabled }}
{{- if .Values.azuremanagedprometheus.use_azuremanagedprometheus }}
apiVersion: azmonitoring.coreos.com/v1
{{- else }}
apiVersion: monitoring.coreos.com/v1
{{- end }}
kind: ServiceMonitor
metadata:
  name: {{ include "kafka-exporter.fullname" . }}
  {{- if .Values.prometheus.serviceMonitor.namespace }}
  namespace: {{ .Values.prometheus.serviceMonitor.namespace }}
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ include "kafka-exporter.name" . }}
    helm.sh/chart: {{ include "kafka-exporter.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- if .Values.labels -}}
    {{ .Values.labels | toYaml | nindent 4 -}}
    {{- end }}
    {{- if .Values.prometheus.serviceMonitor.additionalLabels }}
{{ toYaml .Values.prometheus.serviceMonitor.additionalLabels | indent 4 -}}
    {{- end }}
spec:
  jobLabel: jobLabel
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "kafka-exporter.name" . }}
      helm.sh/chart: {{ include "kafka-exporter.chart" . }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  endpoints:
  - port: metrics
    interval: {{ .Values.prometheus.serviceMonitor.interval }}
    {{- if .Values.prometheus.serviceMonitor.scrapeTimeout }}
    scrapeTimeout: {{ .Values.prometheus.serviceMonitor.scrapeTimeout }}
    {{- end }}
    {{- if .Values.prometheus.serviceMonitor.metricRelabelings }}
    metricRelabelings:
    {{- toYaml .Values.prometheus.serviceMonitor.metricRelabelings | nindent 4 }}
  {{- end }}
  {{- end }}
