name: Build

on:
  push:
    branches: [trunk]
  pull_request:
    branches: [trunk]
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  id-token: write
  security-events: write
  issues: read
  checks: write
  pull-requests: write

jobs:
  analyze:
    name: Analyze
    runs-on: elvia-runner
    if: github.ref != 'refs/heads/trunk' # only run analyze on PR
    steps:
      - uses: 3lvia/core-github-actions-templates/analyze@trunk

  build:
    name: Build and Scan
    runs-on: elvia-runner
    environment: build
    steps:
      - uses: 3lvia/core-github-actions-templates/build@trunk
        with:
          name: github-metrics
          namespace: core
          dockerfile: Dockerfile
          AZURE_CLIENT_ID: ${{ vars.ACR_CLIENT_ID }}
